# Generated by Django 5.0.2 on 2024-07-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('java', models.TextField()),
                ('python', models.TextField()),
                ('html', models.TextField()),
                ('ruby', models.TextField()),
                ('datascience', models.TextField()),
            ],
        ),
    ]
