# Generated by Django 5.0.2 on 2024-07-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sas',
            new_name='Sas_view',
        ),
    ]
