# Generated by Django 5.0.2 on 2024-07-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_sas_sas_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('education_major', models.TextField()),
                ('years_of_experience', models.IntegerField()),
            ],
        ),
    ]
